### ISSUE TITLE
Import AES 256 private key

### ISSUE THREAD

**Issue by tianxun-ng** [Infineon/pkcs11-optiga-tpm#2]
I'm just wondering if there's any function I could call to import AES256 to TPM SLB 9670.

Since this TPM doesn't support generating AES256 itself, so would it make sense to import the AES256 key generated outside of it? Then PKCS#11 program (e.g. python, c/c++ PKCS#11 API) could retrieve the private key from it.

Thanks.

**Comment by wxleong** [comment]
The example is not available here, but you should be able to do so using the C_CreateObject to create an CKO_DATA object. You may place the AES key in the CKA_VALUE field. [CKA_VALUE fields are encrypted for CKO_DATA objects](https://github.com/tpm2-software/tpm2-pkcs11/blob/11fd2532ce10e97834a57dfb25bff6c613a5a851/src/lib/object.c#L702)

**Comment by tianxun-ng** [comment]
Thanks for your reply, it is possible to import the private through pkcs11-tool? 

For example,
https://github.com/OpenSC/OpenSC/issues/2477

As we are looking for a way to meet the AVS (Amazon Voice Services) requirement which needed AES256 token stored in SLB 9670.

Thanks.

**Comment by wxleong** [comment]
Try the following, you will need this [environment](https://github.com/Infineon/pkcs11-optiga-tpm/tree/main/fapi-backend):

```
$ alias tpm2pkcs11-tool='pkcs11-tool --module /usr/local/lib/libtpm2_pkcs11.so'
$ tpm2pkcs11-tool --slot 1 --generate-random 32 > data.write
$ tpm2pkcs11-tool --slot 1 --write-object data.write --type data --application-label data_00 --label data_00 --login --pin userpin --private
$ tpm2pkcs11-tool --slot 1 --read-object --type data --login --pin userpin --label data_00 > data.read
$ diff data.write data.read
```

**Comment by tianxun-ng** [comment]
Appreciate your help, will try out and update soon. Thanks! =)

**Comment by tianxun-ng** [comment]
Thanks, the tutorial works as it successfully imported the data object. Would it be possible if I import it as an AES256 private key? 

For example,
`tpm2pkcs11-tool --slot 1 --write-object data.write --type privkey  --label data_00 --login --pin userpin --private --sensitive`

* With privkey and sensitive flags

As we wish to be able to see something like this,
*******************************************************************************
Available slots:
Slot 0 (0x690a7cc4): SoftHSM slot ID 0x690a7cc4
  token label        : ACSDK
  token manufacturer : SoftHSM project
  token model        : SoftHSM v2
  token flags        : login required, rng, token initialized, PIN initialized, other flags=0x20
  hardware version   : 2.2
  firmware version   : 2.2
  serial num         : dc4d8ada690a7cc4
  pin min/max        : 4/255
Slot 1 (0x1): SoftHSM slot ID 0x1
  token state:   uninitialized
Using slot 0 with a present token (0x690a7cc4)
Secret Key Object; AES length 32
warning: PKCS11 function C_GetAttributeValue(VALUE) failed: rv = CKR_ATTRIBUTE_SENSITIVE (0x11)

  label:      acsdkMain
  Usage:      encrypt, decrypt, verify, wrap, unwrap
*******************************************************************************

Notice that slot 1 is filled with AES256 private key object.

Thanks!

**Comment by wxleong** [comment]
What you are looking for is `--type secrkey` (i.e., CKO_SECRET_KEY) for symmetric key; however, I believe it is not supported by [tpm2-pkcs11](https://github.com/tpm2-software/tpm2-pkcs11) library, you may check [here](https://github.com/tpm2-software/tpm2-pkcs11/blob/1.6.0/src/lib/object.c#L1137), the C_CreateObject only supports CKO_PUBLIC_KEY+CKK_RSA, CKO_DATA, and CKO_CERTIFICATE.

**Comment by wxleong** [comment]
In addition, check [here](https://github.com/tpm2-software/tpm2-pkcs11/blob/1.6.0/src/pkcs11.c#L610), the [tpm2-pkcs11](https://github.com/tpm2-software/tpm2-pkcs11) library has no support for symmetric key operation.

**Comment by tianxun-ng** [comment]
Yes, I think you are right that the library doesn't support importing symmetric keys as I tried the command and get the following output,
`tpm2pkcs11-tool --slot 1 --write-object data.der --type secrkey --label data_00 --login --pin userpin --private --se
nsitive`
`ERROR: Can only create RSA Public key objects or data objects, CKA_CLASS(4), CKA_KEY_TYPE(16)
error: PKCS11 function C_CreateObject failed: rv = CKR_ATTRIBUTE_VALUE_INVALID (0x13)
Aborting.`

However for key generation,
I remember I use a command before and it works, it can generate the private key in slot 1 after initializing the token in slot 0 with the command below.
`./tpm2_ptool.py addkey --algorithm=aes128 --label=avs --userpin=123456 --key-label=avskey --path=/opt/tpm2-pkcs11/`
- tpm2_ptool.py from https://github.com/tpm2-software/tpm2-pkcs11/tree/master/tools

But it doesn't work when I changed the --algorithm field to aes256 (Seems like hardware limitation?).

Is it possible its a hardware instead of software ([tpm2-pkcs11](https://github.com/tpm2-software/tpm2-pkcs11)) limitation? By the way, I'm using SLB 9670.

Thanks!

**Comment by wxleong** [comment]
You are correct, SLB 9670 does not support AES operation. To answer why `./tpm2_ptool.py` may work, this is because you can create AES key, but there is no way to use it. Because EncryptDecrypt command code is not supported. Use `tpm2_getcap commands` to check what command codes are supported by a TPM

**Comment by tianxun-ng** [comment]
Hmm, I see, that's funny haha... that means SLB 9670 could not support the required operations (AES related).

Thanks for the command, i tried to run it,
`root@cobra:~# tpm2_getcap algorithms
rsa:
  value:      0x1
  asymmetric: 1
  symmetric:  0
  hash:       0
  object:     1
  reserved:   0x0
  signing:    0
  encrypting: 0
  method:     0
sha1:
  value:      0x4
  asymmetric: 0
  symmetric:  0
  hash:       1
  object:     0
  reserved:   0x0
  signing:    0
  encrypting: 0
  method:     0
hmac:
  value:      0x5
  asymmetric: 0
  symmetric:  0
  hash:       1
  object:     0
  reserved:   0x0
  signing:    1
  encrypting: 0
  method:     0
aes:
  value:      0x6
  asymmetric: 0
  symmetric:  1
  hash:       0
  object:     0
  reserved:   0x0
  signing:    0
  encrypting: 0
  method:     0`
- Seems like there is one output related to AES. Not really sure what it means though.

Do you manage to know if there is any Infineon TPM product that would provide AES key generation/operations with PKCS#11 compliance?

Thanks!

**Comment by wxleong** [comment]
SLB 9670 supports AES algorithm, it is there for internal operation use, but not available for external use. The new [OPTIGA™ TPM SLB 9672 FW 16.xx](https://www.infineon.com/cms/en/product/security-smart-card-solutions/optiga-embedded-security-solutions/optiga-tpm/optiga-tpm-slb-9672/) supports AES for external use.

**Comment by tianxun-ng** [comment]
Ok, noted with thanks, I think I can close the case now, thanks for your explanations!

**Comment by jpiwek** [comment]
I am using SL 9670 Iridium Kit with RASPI4  and struggeling to import a RSA private key with PKCS#11.
Why it says I can just create public key objects? Do I need to init the slot with additional priviliges or so?

this is the error message:
`Using slot with index 1 (0x2)
ERROR: Can only create RSA Public key objects or data objects, CKA_CLASS(3), CKA_KEY_TYPE(0)
error: PKCS11 function C_CreateObject failed: rv = CKR_ATTRIBUTE_VALUE_INVALID (0x13)
`
