### ISSUE TITLE
Import of RSA2K Key with SLx 9670  

### ISSUE THREAD

**Issue by jpiwek** [Infineon/pkcs11-optiga-tpm#3]
I am using SL 9670 Iridium Kit with RASPI4  and struggeling to import a RSA private key with PKCS#11.
Why it says I can just create public key objects? Do I need to init the slot with additional priviliges or so?

1. **Create Token:**
pkcs11-tool --module /lib/aarch64-linux-gnu/libtpm2_pkcs11.so.1.9.0 --slot-index=1 --init-token --label="import_token" --so-pin="1234"

2. **Add user PIN**
pkcs11-tool --module /lib/aarch64-linux-gnu/libtpm2_pkcs11.so.1.9.0 --slot-index=1 --init-pin --so-pin="1234" --login --pin="5678"

3. **List objects and private secrets with USER PIN:**
pkcs11-tool --module /lib/aarch64-linux-gnu/libtpm2_pkcs11.so.1.9.0 --slot-index=1 --list-objects --login --pin 5678
4. **Import RSA2K Key:**
pkcs11-tool --module /lib/aarch64-linux-gnu/libtpm2_pkcs11.so.1.9.0 --slot-index=1 --write-object rsakey.key --type privkey --id 1234 --login

**this is the error message:**
`Using slot with index 1 (0x2)
ERROR: Can only create RSA Public key objects or data objects, CKA_CLASS(3), CKA_KEY_TYPE(0)
error: PKCS11 function C_CreateObject failed: rv = CKR_ATTRIBUTE_VALUE_INVALID (0x13)
`

**Comment by wxleong** [comment]
Take note that there are a few ways to import a TPM key into a PKCS #11 token:

- During PKCS #11 token creation, find this in [tpm-appnote-pkcs11.pdf](https://github.com/Infineon/pkcs11-optiga-tpm/blob/main/documents/tpm-appnote-pkcs11.pdf):
  - Link Existing (Keys stored outside of a TPM)
  - Link Existing (Keys stored in a TPM NV area)
  - Link Existing (Key persisted in a TPM). 
    *This approach is not supported by the tpm2-pkcs11 project, and custom [patching](https://github.com/Infineon/pkcs11-optiga-tpm/blob/main/patches/interoperability-with-existing-TPM2-persistent-objec.patch) is required.*
- After PKCS #11 token creation:
  - [Import TPM Persistent Key Pair (RSA)](https://github.com/Infineon/pkcs11-optiga-tpm/tree/main/fapi-backend#import-tpm-persistent-key-pair-rsa). 
    *This approach is not supported by the tpm2-pkcs11 project, and custom [patching](https://github.com/Infineon/pkcs11-optiga-tpm/blob/main/fapi-backend/patches/implement-custom-api-c_importkeypair.patch) is required.*

**The recommendation is to use the default mechanism provided by tpm2-pkcs11.**

**Comment by jpiwek** [comment]
Can I bypass step 1 (PKCS#11 Token creation) in case I have a persistent key alreday generated in the TPM2?

Thanks Wen Xin!

**Comment by wxleong** [comment]
What you are asking for is the **After PKCS #11 Token Creation** step I previously highlighted. However, as I mentioned, this is not the standard process provided by tpm2-pkcs11. To clarify:

**During PKCS #11 Token Creation**: This implies that the TPM is equipped with a pre-generated key prior to the creation of the PKCS #11 token. Throughout the creation process, this key is incorporated into the token.

**After PKCS #11 Token Creation**: This indicates that subsequent to the token's establishment, you have the option to generate a TPM key using alternative tools like tpm2-tools and then integrate that key into the existing token.
